Implement file deleting
Xkonti/file-api pull request #39
Opened 2023-10-13 20:54 UTC by mihilt

close #22

<kbd>![image](https://github.com/Xkonti/file-api/assets/50368758/ac2c3627-edbd-4ed4-a0ff-c531cdfaf6e3)</kbd>
reference: https://bun.sh/guides/write-file/unlink

There is no built-in module in Bun to delete a file like `Bun.write`. So I found this way from Bun’s official docs.

2023-10-13 21:26 UTC, Xkonti requested changes
Looks great! There are some issues in tests though:
```
2 tests failed:
(fail) should return a 400 if the path is invalid [0.62ms]
(fail) should return a 400 if the file does not exist [0.38ms]
```

2023-10-13 21:26 UTC, Xkonti commented on src/endpoints/file/deleteFile.test.ts
> +    expect(response.status).toBe(204);
A check to see if the file was actually deleted would be very helpful here.

2023-10-13 21:26 UTC, Xkonti commented on src/endpoints/file/deleteFile.test.ts
> +  expect(response.status).toBe(404);
A check to see if the directory is still there would be very helpful here.

2023-10-13 21:26 UTC, Xkonti commented on src/utils/fileUtils.ts
> +export async function deleteFile(path: string): Promise<Result<boolean, string>> {
I would recommend adding direct tests of this functionality just to make sure that it does what it's supposed to on it's own.

2023-10-13 22:05 UTC, mihilt commented
> Looks great! There are some issues in tests though:
> 
> ```
> 2 tests failed:
> (fail) should return a 400 if the path is invalid [0.62ms]
> (fail) should return a 400 if the file does not exist [0.38ms]
> ```

If I don't put a delay between `beforeEach` and `afterEach`, an error occurs.
(like: `await new Promise (resolve => setTimeout (resolve, 1000);`)

But I didn't do that because other test files didn't do that.

2023-10-26 15:18 UTC, Xkonti commented
@mihilt I will be looking into the testing issue this weekend. Similar problem was encountered in #40

2023-10-31 15:11 UTC, Xkonti approved these changes

2023-10-31 15:12 UTC, merged